const routes = {
  home:["Trang chủ","home"], courses:["Khoá học","book-open"], decks:["Bộ từ vựng","layers"],
  practice:["Luyện tập","pen-tool"], exam:["Luyện thi","file-check"], community:["Cộng đồng","users"],
  stats:["Thống kê","bar-chart-3"], calendar:["Lịch học","calendar"], leaderboard:["Bảng xếp hạng","trophy"],
  settings:["Cài đặt","settings"]
};
const topRoutes=[
  {route:"home",label:"Trang chủ",icon:"home"},
  {route:"courses",label:"Khóa học",icon:"graduation-cap"},
  {route:"decks",label:"Đã tạo",icon:"folder"},
  {route:"community",label:"Lớp học",icon:"users"},
  {route:"leaderboard",label:"Xếp hạng",icon:"trophy"}
];
const mainRoutes=["home","courses","decks","practice","exam","community"];
const toolRoutes=["stats","calendar","leaderboard","settings"];
const decks=[
  {id:1,name:"Hán Việt cơ bản",term:"基礎漢越",total:200,learned:156,newCount:12,icon:"🎯"},
  {id:2,name:"TOPIK II từ vựng",term:"TOPIK II",total:500,learned:287,newCount:25,icon:"🇰🇷"},
  {id:3,name:"Thành ngữ Hán Việt",term:"成語",total:150,learned:89,newCount:8,icon:"📚"},
  {id:4,name:"Chữ Hán theo chủ đề",term:"主題漢字",total:300,learned:134,newCount:18,icon:"🏷️"},
  {id:5,name:"Hán Việt giao tiếp",term:"交際",total:180,learned:45,newCount:30,icon:"💬"},
  {id:6,name:"Từ vựng N3",term:"N3語彙",total:400,learned:210,newCount:15,icon:"🇯🇵"}
];
const courses=[
  {id:1,name:"Hán Việt TOPIK II - Khóa đầy đủ",level:"Trung cấp",lessons:48,done:31,icon:"🇰🇷"},
  {id:2,name:"250 thành ngữ Hán Việt thông dụng",level:"Cơ bản → Nâng cao",lessons:30,done:12,icon:"📚"},
  {id:3,name:"Chữ Hán theo chủ đề hàng ngày",level:"Sơ cấp",lessons:60,done:8,icon:"🏷️"}
];
const words=[
  {term:"勉強",reading:"Miện cường",meaning:"Học tập, nỗ lực"},
  {term:"學習",reading:"Học tập",meaning:"Tiếp thu kiến thức"},
  {term:"經濟",reading:"Kinh tế",meaning:"Hoạt động sản xuất và trao đổi"},
  {term:"社會",reading:"Xã hội",meaning:"Cộng đồng con người"},
  {term:"文化",reading:"Văn hóa",meaning:"Giá trị vật chất và tinh thần"},
  {term:"自然",reading:"Tự nhiên",meaning:"Thế giới không do con người tạo ra"}
];
const quizQuestions=[
  {q:"經濟 có âm Hán Việt là gì?",options:["Kinh tế","Văn hóa","Xã hội","Tự nhiên"],answer:0},
  {q:"社會 nghĩa là gì?",options:["Học tập","Xã hội","Kinh tế","Văn hóa"],answer:1},
  {q:"Chữ nào mang nghĩa “văn hóa”?",options:["自然","學習","文化","經濟"],answer:2}
];
const blankDraftCard=()=>({term:"",definition:"",pronunciation:"",wordType:"",example:"",synonyms:"",image:""});
const defaultLearnSettings={answerDefinition:true,answerTerm:false,starredOnly:false,unmasteredOnly:false,inOrder:false,acceptSynonyms:true,autoAdvance:true,fillBlank:false,multipleChoice:true};
const defaultUser={name:"Khách",email:"",picture:"",sub:"",signedIn:false};
const defaultState={route:"home",streak:7,today:146,minutes:42,xp:2340,quizIndex:0,quizScore:0,quizAnswered:null,flashIndex:0,activeCreatedDeck:null,detailCardIndex:0,detailFlipped:false,detailMode:"flashcard",detailSort:"original",detailProgress:{},detailStars:{},learnOrder:[],learnIndex:0,learnOptions:[],learnAnswered:null,learnCorrect:0,learnUnknown:0,learnCompleted:0,learnSettings:defaultLearnSettings,theme:"dark",dailyGoal:30,notifications:true,calendar:[2,4,6,8,10,12,14,16,18,20,22,24,26],favorites:[1,2],user:defaultUser,createdDecks:[],deckDraft:{title:"",description:"",isPublic:false,suggestions:true,cards:[blankDraftCard()]}};
const googleClientId=document.querySelector('meta[name="google-signin-client_id"]')?.content?.trim()||"";
const freshDefaultState=()=>JSON.parse(JSON.stringify(defaultState));
let state={...freshDefaultState(),...JSON.parse(localStorage.getItem("hvq-state")||"{}")};
state.user={...defaultUser,...(state.user||{})};
state.deckDraft={...defaultState.deckDraft,...(state.deckDraft||{})};
state.deckDraft.cards=state.deckDraft.cards?.length?state.deckDraft.cards.map(card=>({...blankDraftCard(),...card})):[blankDraftCard()];
state.learnSettings={...defaultLearnSettings,...(state.learnSettings||{})};
const app=document.querySelector("#app");

function save(){localStorage.setItem("hvq-state",JSON.stringify(state))}
function escapeHtml(value=""){return String(value).replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[ch]))}
function escapeAttr(value=""){return escapeHtml(value)}
function icon(name){return `<span class="iconify" data-icon="lucide:${name}"></span>`}
function button(label,action,kind=""){return `<button class="button ${kind}" data-action="${action}">${label}</button>`}
function progress(value){return `<div class="progress"><i style="width:${value}%"></i></div>`}
function header(title,subtitle,actions=""){return `<header class="page-header"><div><h1>${title}</h1><p>${subtitle}</p></div><div class="flex flex-wrap gap-2">${actions}</div></header>`}
function showToast(text,ico="check-circle"){const el=document.querySelector("#toast");el.querySelector("#toastIcon").dataset.icon=`lucide:${ico}`;el.querySelector("#toastText").textContent=text;el.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>el.classList.remove("show"),2200)}
function modal(title,body){document.querySelector("#modalTitle").textContent=title;document.querySelector("#modalBody").innerHTML=body;document.querySelector("#modal").classList.add("show")}
function closeModal(){document.querySelector("#modal").classList.remove("show");document.querySelector(".modal-card")?.classList.remove("import-modal","learn-settings-modal")}
function currentUser(){return state.user?.signedIn?state.user:{...defaultUser,name:"Khách"}}
function initials(name="Khách"){return name.trim().split(/\s+/).map(x=>x[0]).join("").slice(-2).toUpperCase()||"HV"}
function userAvatar(user=currentUser()){return user.picture?`<img class="avatar avatar-image" src="${escapeAttr(user.picture)}" alt="${escapeAttr(user.name)}">`:`<span class="avatar">${initials(user.name)}</span>`}
function isGoogleConfigured(){return googleClientId&&googleClientId.includes(".apps.googleusercontent.com")&&!googleClientId.startsWith("PASTE_")}
function parseJwt(token){try{let payload=token.split(".")[1].replace(/-/g,"+").replace(/_/g,"/");payload+=Array((4-payload.length%4)%4+1).join("=");return JSON.parse(decodeURIComponent(atob(payload).split("").map(c=>`%${("00"+c.charCodeAt(0).toString(16)).slice(-2)}`).join("")))}catch{return null}}
function handleGoogleCredential(response){const profile=parseJwt(response.credential);if(!profile){showToast("Không đọc được phản hồi từ Google","circle-alert");return}state.user={name:profile.name||profile.given_name||"Người dùng Google",email:profile.email||"",picture:profile.picture||"",sub:profile.sub||"",signedIn:true};save();closeModal();render();showToast(`Xin chào ${state.user.name}`)}
function openLoginModal(){modal("Đăng nhập",`<div class="login-panel"><div class="login-icon">${icon("user-round-check")}</div><h3>Đăng nhập HanVietQuiz</h3><p class="muted text-sm">Dùng tài khoản Google để hiển thị hồ sơ và lưu phiên học trên trình duyệt này.</p><div id="googleSignInButton" class="google-signin-slot"></div>${isGoogleConfigured()?"":`<p class="auth-note">${icon("circle-alert")} Chưa có Google Client ID. Hãy thay giá trị meta <strong>google-signin-client_id</strong> trong index.html.</p>`}</div>`);renderGoogleButton()}
function signOut(){if(window.google?.accounts?.id)google.accounts.id.disableAutoSelect();state.user={...defaultUser};save();render();showToast("Đã đăng xuất")}
function renderUserUi(){const user=currentUser();const buttonEl=document.querySelector("#profileButton");buttonEl.innerHTML=`${userAvatar(user)}<span class="hidden sm:inline">${escapeHtml(user.name)}</span>`;document.querySelector("#profileMenu").innerHTML=user.signedIn?`<div class="profile-summary">${userAvatar(user)}<div><strong>${escapeHtml(user.name)}</strong><small>${escapeHtml(user.email||"Đã đăng nhập Google")}</small></div></div><button class="dropdown-item" data-route="settings">Hồ sơ & cài đặt</button><button class="dropdown-item" data-action="upgrade">Nâng cấp Pro</button><button class="dropdown-item text-red-400" data-action="sign-out">Đăng xuất</button>`:`<div class="profile-summary"><span class="avatar">HV</span><div><strong>Khách</strong><small>Đăng nhập để cá nhân hóa hồ sơ</small></div></div><button class="dropdown-item" data-action="sign-in-google">${icon("log-in")} Đăng nhập Google</button><button class="dropdown-item" data-route="settings">Cài đặt</button>`}
function renderGoogleButton(){if(!isGoogleConfigured())return;const target=document.querySelector("#googleSignInButton");if(!target||!window.google?.accounts?.id)return;target.innerHTML="";google.accounts.id.initialize({client_id:googleClientId,callback:handleGoogleCredential,auto_select:false});google.accounts.id.renderButton(target,{theme:"filled_black",size:"large",type:"standard",shape:"pill",text:"signin_with",logo_alignment:"left",locale:"vi",width:260})}
window.initGoogleAuth=()=>renderGoogleButton();

function renderNav(){
  document.querySelector("#topNav").innerHTML=topRoutes.map(item=>`
    <button class="nav-button ${(state.route===item.route||(["createDeck","deckDetail"].includes(state.route)&&item.route==="decks"))?"active":""}" data-route="${item.route}">
      ${icon(item.icon)}<span>${item.label}</span>
    </button>
  `).join("");
  document.querySelector("#mainSidebar").innerHTML=mainRoutes.map(k=>`<button class="sidebar-button ${(state.route===k||(["createDeck","deckDetail"].includes(state.route)&&k==="decks"))?"active":""}" data-route="${k}">${icon(routes[k][1])}<span>${routes[k][0]}</span>${k==="courses"?'<span class="badge">3</span>':""}</button>`).join("");
  document.querySelector("#toolSidebar").innerHTML=toolRoutes.map(k=>`<button class="sidebar-button ${state.route===k?"active":""}" data-route="${k}">${icon(routes[k][1])}<span>${routes[k][0]}</span></button>`).join("");
}
function routeTo(route){if(!routes[route])route="home";state.route=route;save();render()}

function deckCards(limit=99){return `<div class="deck-grid">${decks.slice(0,limit).map(d=>{const pct=Math.round(d.learned/d.total*100);return `<article class="card card-hover deck-card" data-deck="${d.id}"><div class="flex justify-between"><span class="text-xl">${d.icon}</span><span class="pill">${d.newCount} mới</span></div><h3>${d.name}</h3><p>${d.term} · ${d.learned}/${d.total}</p><div class="mt-3">${progress(pct)}</div><div class="flex justify-between items-center mt-2"><small class="muted">${pct}%</small><button class="button small" data-study="${d.id}">Học</button></div></article>`}).join("")}</div>`}
function courseRows(){return courses.map(c=>{const pct=Math.round(c.done/c.lessons*100);return `<article class="card card-hover course-row" data-course="${c.id}"><span class="item-icon">${c.icon}</span><div class="row-main"><h3>${c.name}</h3><p>${c.level} · ${c.done}/${c.lessons} bài</p><div class="mt-2">${progress(pct)}</div></div><strong class="text-indigo-400">${pct}%</strong></article>`}).join("")}

function homePage(){
  const user=currentUser(),firstName=user.name.split(/\s+/).filter(Boolean).slice(-1)[0]||user.name;
  const loginAction=user.signedIn?"":button(`${icon("log-in")} Đăng nhập Google`,"sign-in-google");
  return header(`Xin chào, ${escapeHtml(firstName)} 👋`,"Hãy tiếp tục hành trình chinh phục Hán Việt nhé!",loginAction+button(`${icon("rotate-ccw")} Ôn tập nhanh`,"review")+button(`${icon("play")} Học ngay`,"study","primary"))+
  `<div class="grid-dashboard">
    <div class="stack">
      <section class="card section-card"><div class="section-title"><h2>${icon("activity")} Hoạt động học tập</h2></div><div class="stats-grid"><div class="stat"><strong class="text-indigo-400">${state.today}</strong><small>Câu hôm nay</small></div><div class="stat"><strong class="text-emerald-400">${state.minutes}m</strong><small>Thời gian</small></div></div><div class="mt-4"><div class="flex justify-between text-xs mb-2"><span>Mục tiêu ngày</span><span>${Math.min(100,Math.round(state.today/state.dailyGoal*100))}%</span></div>${progress(Math.min(100,state.today/state.dailyGoal*100))}</div><div class="mt-5 p-4 rounded-xl bg-amber-500/10"><strong>🔥 ${state.streak} ngày liên tục</strong><p class="muted text-xs mt-1">Học thêm hôm nay để giữ chuỗi.</p></div></section>
      <section class="card section-card"><div class="section-title"><h2>${icon("star")} Cấp độ</h2><span class="pill">Lv.12</span></div><strong>Học giả Hán Việt</strong><p class="muted text-xs my-2">${state.xp.toLocaleString()} / 3.000 XP</p>${progress(state.xp/30)}</section>
    </div>
    <div class="stack">
      <section><div class="section-title"><h2>${icon("layers")} Bộ từ đang học</h2><button class="button small" data-route="decks">Xem tất cả</button></div>${deckCards(4)}</section>
      <section><div class="section-title"><h2>${icon("graduation-cap")} Khóa đang học</h2><button class="button small" data-route="courses">Xem tất cả</button></div><div class="stack gap-3">${courseRows()}</div></section>
    </div>
    <div class="stack">
      <section class="card section-card"><div class="section-title"><h2>${icon("play-circle")} Tiếp tục học</h2></div>${decks.slice(0,3).map(d=>`<div class="list-row card-hover" data-study="${d.id}"><span class="item-icon">${d.icon}</span><div class="row-main"><strong>${d.name}</strong><small>Còn ${d.newCount} từ mới</small></div>${icon("chevron-right")}</div>`).join("")}</section>
      <section class="card section-card"><div class="section-title"><h2>${icon("sparkles")} Từ mới hôm nay</h2></div><div class="text-center"><div class="text-5xl font-bold text-indigo-400">勉強</div><p class="mt-3 font-semibold">Miện cường</p><p class="muted text-sm">Học tập, nỗ lực</p><button class="button small mt-4" data-speak="勉強">${icon("volume-2")} Nghe</button></div></section>
      <section class="card section-card"><div class="section-title"><h2>${icon("zap")} Công cụ nhanh</h2></div><div class="grid grid-cols-2 gap-2">${button("Flashcard","flashcard")}${button("Quiz nhanh","quiz")}${button("Tra từ","dictionary")}${button("Thống kê","stats")}</div></section>
    </div>
  </div>`;
}
function coursesPage(){return header("Khoá học","Theo dõi tiến độ và tiếp tục bài học của bạn.",button(`${icon("plus")} Tạo khóa học`,"new-course","primary"))+`<div class="tabs">${["Tất cả","Đang học","Đã hoàn thành"].map((x,i)=>`<button class="tab-button ${i===0?"active":""}" data-filter-course="${i}">${x}</button>`).join("")}</div><div id="courseResults" class="stack">${courseRows()}</div>`}
function decksPage(){const created=state.createdDecks||[];return header("Đã tạo","Quản lý các bộ thẻ của bạn và bắt đầu học.",button(`${icon("plus")} Tạo bộ thẻ mới`,"new-deck","primary"))+`${created.length?`<section class="mb-7"><div class="section-title"><h2>${icon("folder")} Bộ thẻ của tôi</h2><span class="pill">${created.length} bộ</span></div><div class="deck-grid">${created.map((d,i)=>`<article class="card card-hover deck-card" data-created-deck="${i}"><div class="flex justify-between"><span class="text-xl">📁</span><span class="pill">${d.isPublic?"Công khai":"Riêng tư"}</span></div><h3>${escapeHtml(d.title)}</h3><p>${d.cards.length} thẻ · ${escapeHtml(d.description||"Không có mô tả")}</p><div class="flex gap-2 mt-4"><button class="button small primary" data-study-created="${i}">${icon("play")} Học ngay</button><button class="button small" data-edit-created="${i}">Chỉnh sửa</button><button class="button small danger" data-delete-created="${i}">Xóa</button></div></article>`).join("")}</div></section>`:""}<div class="flex gap-3 mb-5"><input id="deckSearch" class="input" placeholder="Tìm bộ từ..."><select id="deckSort" class="input max-w-[180px]"><option value="name">Theo tên</option><option value="progress">Theo tiến độ</option></select></div><div id="deckResults">${deckCards()}</div>`}
function createDeckPage(){const d=state.deckDraft;return `<div class="creator-page">
  <div class="creator-toolbar"><h1>Tạo bộ thẻ mới</h1><div class="creator-actions">
    <button class="button" data-action="import-cards">${icon("upload")} Nhập</button>
    <button class="button" data-action="auto-fill">${icon("sparkles")} ${icon("image")}</button>
    <button class="public-toggle ${d.isPublic?"on":""}" data-action="toggle-public">${icon("globe")} Công khai <span class="switch"></span></button>
    <button class="button" data-action="cancel-create">Hủy</button>
    <button class="button primary" data-action="save-deck">Tạo</button>
  </div></div>
  <div class="creator-meta">
    <div class="editor-field"><label>Tiêu đề</label><input class="creator-input" data-draft-meta="title" value="${escapeAttr(d.title)}" placeholder="Thêm tiêu đề..."></div>
    <div class="editor-field"><label>Mô tả <small>(Tùy chọn)</small></label><textarea class="creator-input" data-draft-meta="description" placeholder="Thêm mô tả cho bộ thẻ của bạn...">${escapeHtml(d.description)}</textarea></div>
  </div>
  <div class="creator-subbar"><button class="${d.suggestions?"suggest-enabled":""}" data-action="toggle-suggestions">${icon("sparkles")} Gợi ý: ${d.suggestions?"Bật":"Tắt"}</button><button data-action="delete-draft">${icon("trash-2")} Xóa Bản Nháp</button></div>
  <div class="card-editor-list">${d.cards.map(cardEditor).join("")}</div>
  <div class="add-card-row"><button class="button" data-action="add-card">${icon("plus")} Thêm thẻ</button></div>
</div>`}
function cardEditor(card,index){return `<article class="card-editor" data-card-index="${index}"><span class="card-number">${index+1}</span><div class="card-editor-grid">
  <div class="editor-field"><label>THUẬT NGỮ</label><textarea class="creator-input large" data-card-field="term" placeholder="Nhập thuật ngữ">${escapeHtml(card.term)}</textarea></div>
  <div class="editor-field"><label>ĐỊNH NGHĨA</label><textarea class="creator-input large" data-card-field="definition" placeholder="Nhập định nghĩa">${escapeHtml(card.definition)}</textarea></div>
  <div class="editor-field"><label>Phát âm <small>(Tùy chọn)</small></label><input class="creator-input" data-card-field="pronunciation" value="${escapeAttr(card.pronunciation)}" placeholder="VD: /həˈloʊ/"></div>
  <div class="editor-field"><label>Loại từ <small>(Tùy chọn)</small></label><input class="creator-input" data-card-field="wordType" value="${escapeAttr(card.wordType)}" placeholder="VD: noun, verb..."></div>
  <div class="editor-field"><label>Ví dụ <small>(Tùy chọn)</small></label><textarea class="creator-input" data-card-field="example" placeholder="Nhập câu ví dụ">${escapeHtml(card.example)}</textarea></div>
  <div class="editor-field"><label>Từ đồng nghĩa <small>(Tùy chọn)</small></label><textarea class="creator-input" data-card-field="synonyms" placeholder="Nhập các từ đồng nghĩa, cách nhau bằng dấu chấm phẩy (;)">${escapeHtml(card.synonyms)}</textarea></div>
  </div><div class="card-side-actions">
    <button data-remove-card="${index}" title="Xóa thẻ">${icon("trash-2")}</button>
    <button class="image-picker ${card.image?"has-image":""}" data-image-card="${index}" style="${card.image?`background-image:url('${card.image}')`:""}">${icon("image")}<small>Ảnh</small></button>
    <button data-move-card="${index}" data-direction="-1" title="Di chuyển lên">${icon("chevron-up")}</button>
    <button data-move-card="${index}" data-direction="1" title="Di chuyển xuống">${icon("chevron-down")}</button>
  </div></article>`}
function deckDetailPage(){const deck=state.createdDecks[state.activeCreatedDeck];if(!deck){state.route="decks";return decksPage()}const cards=detailCards(deck);state.detailCardIndex=Math.min(state.detailCardIndex,cards.length-1);const current=cards[state.detailCardIndex];const modes=[["speaking","Speaking","message-square"],["conversation","Hội thoại","message-circle"],["grammar","Ngữ pháp","book-open"],["reading","Đọc hiểu","book-open-check"],["flashcard","Học","graduation-cap"],["test","Kiểm tra","file-check-2"],["dictation","Nghe Chép","grid-3x3"]];return `<div class="deck-detail">
  <button class="detail-back" data-action="back-to-decks">${icon("arrow-left")} Quay lại</button>
  <div class="detail-heading"><h1>${escapeHtml(deck.title)} ${deck.isPublic?icon("globe-2"):""}</h1><div class="detail-heading-actions"><button class="button small" data-action="schedule-review">${icon("calendar-days")} Lặp lại ngắt quãng</button><button class="icon-button" data-action="toggle-deck-bookmark">${icon("bookmark")}</button><button class="icon-button" data-action="share-deck">${icon("share-2")}</button><button class="icon-button" data-action="deck-menu">${icon("more-vertical")}</button></div></div>
  <div class="study-mode-grid">${modes.map(([key,label,ico])=>`<button class="study-mode ${state.detailMode===key?"active":""}" data-detail-mode="${key}">${icon(ico)} ${label}</button>`).join("")}</div>
  <div id="detailStudyPanel">${detailStudyPanel(deck,current,cards)}</div>
  <div class="deck-list-toolbar"><button class="button small" data-edit-created="${state.activeCreatedDeck}">${icon("square-pen")} Chỉnh sửa</button><select id="detailSort" class="sort-select"><option value="original" ${state.detailSort==="original"?"selected":""}>Thứ tự gốc</option><option value="alphabetical" ${state.detailSort==="alphabetical"?"selected":""}>A → Z</option><option value="starred" ${state.detailSort==="starred"?"selected":""}>Đã đánh dấu sao</option></select></div>
  ${detailCardGroups(deck)}
</div>`}
function detailCards(deck){let cards=deck.cards.map((card,originalIndex)=>({...card,originalIndex}));if(state.detailSort==="alphabetical")cards.sort((a,b)=>(a.term||"").localeCompare(b.term||""));if(state.detailSort==="starred")cards.sort((a,b)=>Number(isDetailStarred(b.originalIndex))-Number(isDetailStarred(a.originalIndex)));return cards}
function detailStudyPanel(deck,current,cards){if(state.detailMode!=="flashcard"){const labels={speaking:"Luyện nói",conversation:"Luyện hội thoại",grammar:"Luyện ngữ pháp",reading:"Luyện đọc hiểu",test:"Kiểm tra",dictation:"Nghe chép"};return `<section class="card section-card max-w-2xl mx-auto text-center"><h2>${labels[state.detailMode]}</h2><p class="muted my-4">Chế độ này sử dụng ${deck.cards.length} thẻ trong bộ “${escapeHtml(deck.title)}”.</p><button class="button primary" data-action="start-detail-mode">Bắt đầu</button></section>`}return `<div class="detail-flash-area"><div id="detailFlashcard" class="detail-flashcard ${state.detailFlipped?"flipped":""}"><div class="flash-tools"><button data-action="flash-settings">${icon("sliders-horizontal")}</button><button data-action="edit-current-card">${icon("pencil")} Viết</button></div><div class="front-content">${current.image?`<img src="${current.image}" class="mx-auto mb-5 max-h-28 rounded-xl">`:""}<div class="term">${escapeHtml(current.term||"—")}</div></div><div class="back-content"><h2>${escapeHtml(current.definition||"Chưa có định nghĩa")}</h2>${current.pronunciation?`<p class="text-indigo-300">${escapeHtml(current.pronunciation)}</p>`:""}${current.example?`<p class="muted">${escapeHtml(current.example)}</p>`:""}</div><div class="flash-bottom-tools"><button data-speak="${escapeAttr(current.term)}">${icon("mic")}</button><button data-speak="${escapeAttr(current.term)}">${icon("volume-2")}</button></div></div><div class="shortcut-hint">Phím tắt: ← → để chuyển thẻ · Space / Enter để lật thẻ</div><div class="flash-nav"><button class="button small" data-action="show-progress">${icon("layers")} Tiến độ</button><div class="flash-nav-center"><button class="button" data-detail-nav="-1">${icon("arrow-left")}</button><span>Thẻ ${state.detailCardIndex+1} / ${cards.length}</span><button class="button" data-detail-nav="1">${icon("arrow-right")}</button></div><button class="button flash-nav-right" data-action="shuffle-detail">${icon("shuffle")}</button></div><div class="detail-progress-menu"><button class="${detailStatus(current.originalIndex)==="new"?"active":""}" data-set-status="new">Chưa học</button><button class="${detailStatus(current.originalIndex)==="learning"?"active":""}" data-set-status="learning">Đang học</button><button class="${detailStatus(current.originalIndex)==="mastered"?"active":""}" data-set-status="mastered">Đã thành thạo</button></div><a href="#card-groups" class="detail-link">Xem hướng dẫn cách học</a></div>`}
function detailStatus(cardIndex){return state.detailProgress[`${state.activeCreatedDeck}:${cardIndex}`]||"new"}
function isDetailStarred(cardIndex){return !!state.detailStars[`${state.activeCreatedDeck}:${cardIndex}`]}
function detailCardGroups(deck){const groups=[["starred","⭐ Được đánh dấu sao"],["new","Chưa học"],["learning","Đang học"],["mastered","Đã thành thạo"]];return `<div id="card-groups" class="card-groups">${groups.map(([type,label])=>{const rows=deck.cards.map((card,index)=>({card,index})).filter(x=>type==="starred"?isDetailStarred(x.index):detailStatus(x.index)===type);return `<section><div class="card-group-header"><strong>${label}</strong><span class="muted">${rows.length} thẻ</span></div>${rows.length?rows.map(({card,index})=>`<div class="card-list-row ${type==="learning"?"learning":type==="mastered"?"mastered":""}" data-jump-card="${index}"><strong>${escapeHtml(card.term||"—")}</strong><i class="card-divider"></i><span class="definition-cell">${escapeHtml(card.definition||"Chưa có định nghĩa")}</span><span class="row-actions"><button class="${isDetailStarred(index)?"starred":""}" data-detail-star="${index}">${icon("star")}</button><button data-speak="${escapeAttr(card.term)}">${icon("volume-2")}</button></span></div>`).join(""):'<div class="empty-group">Chưa có thẻ trong nhóm này.</div>'}</section>`}).join("")}</div>`}
function learnSessionPage(){const deck=state.createdDecks[state.activeCreatedDeck];if(!deck){state.route="decks";return decksPage()}if(!state.learnOrder.length)return `<div class="learn-session"><div class="learn-topbar"><button class="learn-exit" data-action="exit-learn">${icon("arrow-left")} Thoát</button><button class="button small" data-action="learn-settings">${icon("settings")} Cài đặt</button></div><section class="card learn-finished"><h1>Không có thẻ phù hợp</h1><p class="muted">Hãy thay đổi bộ lọc trong Cài đặt học tập.</p></section></div>`;if(state.learnCompleted>=state.learnOrder.length)return `<div class="learn-session"><div class="learn-topbar"><button class="learn-exit" data-action="exit-learn">${icon("arrow-left")} Thoát</button></div><section class="card learn-finished"><strong>${state.learnCorrect}/${state.learnOrder.length}</strong><h1>Hoàn thành phiên học!</h1><p class="muted">Bạn đã trả lời đúng ${state.learnCorrect} câu và chọn “Tôi không biết” ${state.learnUnknown} câu.</p><div class="flex justify-center gap-2 mt-6"><button class="button" data-action="exit-learn">Về bộ thẻ</button><button class="button primary" data-action="restart-learn">Học lại</button></div></section></div>`;
  const cardIndex=state.learnOrder[state.learnIndex],card=deck.cards[cardIndex],options=state.learnOptions;
  return `<div class="learn-session"><div class="learn-topbar"><button class="learn-exit" data-action="exit-learn">${icon("arrow-left")} Thoát</button><button class="button small" data-action="learn-settings">${icon("settings")} Cài đặt</button></div>
  <div class="learn-progress">${state.learnOrder.map((_,i)=>`<i class="learn-progress-segment ${i<state.learnCompleted?"done":i===state.learnIndex?"current":""}"></i>`).join("")}<small class="text-indigo-300">+${Math.max(0,state.learnOrder.length-state.learnCompleted)}</small></div>
  <section class="learn-question-card"><div class="learn-question-head"><h1 class="learn-term">${escapeHtml(learnPrompt(card))}</h1><div class="learn-question-tools"><span class="mini-switch"></span><button data-speak="${escapeAttr(card.term)}">${icon("volume-2")}</button><button class="${isDetailStarred(cardIndex)?"starred":""}" data-learn-star="${cardIndex}">${icon("star")}</button><button data-action="edit-learn-card">${icon("pencil")}</button></div></div>
    ${state.learnSettings.fillBlank?`<form id="fillBlankForm" class="mt-8"><input id="fillBlankAnswer" class="input" autocomplete="off" placeholder="Nhập câu trả lời..."><button class="button primary mt-3" ${state.learnAnswered!==null?"disabled":""}>Kiểm tra</button></form>`:`<div class="learn-options">${options.map((option,i)=>{const selected=state.learnAnswered===i,correct=option.cardIndex===cardIndex;return `<button class="learn-option ${state.learnAnswered!==null?(correct?"correct":selected?"wrong":""):""}" data-learn-answer="${i}" ${state.learnAnswered!==null?"disabled":""}><span class="option-number">${i+1}</span><span>${escapeHtml(option.text||"Chưa có định nghĩa")}</span></button>`}).join("")}</div>`}
    ${state.learnAnswered===null?'<button class="dont-know" data-action="learn-unknown">5. Tôi không biết</button>':`<div class="learn-feedback">${state.learnAnswered==="unknown"?"Đáp án: "+escapeHtml(learnAnswer(card)):state.learnAnswered==="fill-correct"?"Chính xác!":state.learnAnswered==="fill-wrong"?"Chưa đúng. Đáp án: "+escapeHtml(learnAnswer(card)):options[state.learnAnswered].cardIndex===cardIndex?"Chính xác!":"Chưa đúng. Đáp án: "+escapeHtml(learnAnswer(card))}<br><button class="button primary small mt-3" data-action="next-learn">Tiếp tục</button></div>`}
  </section><div class="learn-footer"><span>Đã hoàn thành: ${state.learnCompleted}/${state.learnOrder.length}</span><span>•</span><span>Câu hỏi: ${state.learnCompleted+1}</span></div></div>`}
function shuffled(array){const copy=[...array];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
function learnPrompt(card){return state.learnSettings.answerTerm?(card.definition||"—"):(card.term||"—")}
function learnAnswer(card){return state.learnSettings.answerTerm?(card.term||"—"):(card.definition||"—")}
function buildLearnOptions(cardIndex){const deck=state.createdDecks[state.activeCreatedDeck];const pool=deck.cards.map((card,index)=>({cardIndex:index,text:learnAnswer(card)}));const correct=pool.find(x=>x.cardIndex===cardIndex);const wrong=shuffled(pool.filter(x=>x.cardIndex!==cardIndex)).slice(0,3);const fallbacks=["Chưa xác định","Một khái niệm khác","Không thuộc nhóm này","Tất cả đều sai"];while(wrong.length<3)wrong.push({cardIndex:-wrong.length-1,text:fallbacks[wrong.length]});return shuffled([correct,...wrong])}
function practicePage(){
  const tabs=[["flashcard","Flashcard"],["quiz","Quiz nhanh"],["dictionary","Tra từ"]];
  return header("Luyện tập","Chọn phương pháp phù hợp với mục tiêu hôm nay.")+`<div class="tabs">${tabs.map(([k,n],i)=>`<button class="tab-button ${i===0?"active":""}" data-practice-tab="${k}">${n}</button>`).join("")}</div><div id="practicePanel">${flashcardPanel()}</div>`;
}
function currentFlashcards(){if(Number.isInteger(state.activeCreatedDeck)&&state.createdDecks[state.activeCreatedDeck])return state.createdDecks[state.activeCreatedDeck].cards.map(c=>({term:c.term||"—",reading:c.pronunciation||c.wordType||"",meaning:c.definition||"Chưa có định nghĩa",example:c.example||"",synonyms:c.synonyms||"",image:c.image||""}));return words}
function flashcardPanel(){const source=currentFlashcards();const index=(state.flashIndex||0)%source.length;const w=source[index];const title=Number.isInteger(state.activeCreatedDeck)&&state.createdDecks[state.activeCreatedDeck]?state.createdDecks[state.activeCreatedDeck].title:"Flashcard";return `<div class="quiz-shell"><div class="flex justify-between items-center mb-3"><strong>${escapeHtml(title)}</strong><span class="pill">${index+1}/${source.length}</span></div><div id="flashcard" class="card flashcard"><div>${w.image?`<img src="${w.image}" alt="" class="mx-auto mb-5 max-h-32 rounded-xl">`:""}<div class="term">${escapeHtml(w.term)}</div><p class="hint muted mt-4">Chạm để xem đáp án</p><div class="answer">${w.reading?`<p class="text-indigo-400">${escapeHtml(w.reading)}</p>`:""}<h2>${escapeHtml(w.meaning)}</h2>${w.example?`<p class="muted">${escapeHtml(w.example)}</p>`:""}${w.synonyms?`<p class="muted text-sm">Đồng nghĩa: ${escapeHtml(w.synonyms)}</p>`:""}</div></div></div><div class="flex justify-center gap-2 mt-4"><button class="button danger" data-rate="again">Chưa nhớ</button><button class="button" data-rate="hard">Khó</button><button class="button primary" data-rate="easy">Đã nhớ</button></div></div>`}
function quizPanel(){
  const q=quizQuestions[state.quizIndex%quizQuestions.length];
  return `<div class="quiz-shell card section-card"><div class="flex justify-between"><span class="pill">Câu ${state.quizIndex+1}/${quizQuestions.length}</span><strong>${state.quizScore} điểm</strong></div><h2 class="my-6">${q.q}</h2><div>${q.options.map((o,i)=>`<button class="quiz-option ${state.quizAnswered===i?(i===q.answer?"correct":"wrong"):""} ${state.quizAnswered!==null&&i===q.answer?"correct":""}" data-answer="${i}" ${state.quizAnswered!==null?"disabled":""}>${String.fromCharCode(65+i)}. ${o}</button>`).join("")}</div>${state.quizAnswered!==null?`<button class="button primary mt-5" data-action="next-question">Câu tiếp theo</button>`:""}</div>`}
function dictionaryPanel(){return `<div class="card section-card max-w-3xl"><div class="flex gap-2"><input id="dictionaryInput" class="input" placeholder="Nhập chữ Hán, âm Hán Việt hoặc nghĩa..."><button class="button primary" data-action="lookup">Tra từ</button></div><div id="dictionaryResults" class="search-results"><p class="empty">Nhập từ khóa để bắt đầu tra cứu.</p></div></div>`}
function examPage(){return header("Luyện thi","Mô phỏng bài thi với giới hạn thời gian và kết quả chi tiết.",button("Bắt đầu đề mới","start-exam","primary"))+`<div class="grid md:grid-cols-3 gap-4">${[["TOPIK II · Từ vựng","50 câu","60 phút"],["Hán Việt tổng hợp","40 câu","45 phút"],["Thành ngữ nâng cao","30 câu","30 phút"]].map((e,i)=>`<article class="card section-card card-hover"><span class="pill">Đề ${i+1}</span><h2 class="mt-4">${e[0]}</h2><p class="muted text-sm my-3">${e[1]} · ${e[2]}</p>${progress([65,30,0][i])}<button class="button primary w-full mt-5" data-exam="${i}">${i===2?"Bắt đầu":"Làm tiếp"}</button></article>`).join("")}</div>`}
function communityPage(){return header("Cộng đồng","Chia sẻ thành tích, hỏi đáp và học cùng nhau.",button(`${icon("plus")} Đăng bài`,"new-post","primary"))+`<div class="grid lg:grid-cols-[1fr_320px] gap-5"><div id="feed" class="stack">${["Mẹo nhớ 20 từ Hán Việt theo bộ thủ","Mình vừa hoàn thành chuỗi học 30 ngày!","Ai đang ôn TOPIK II cùng mình?"].map((t,i)=>`<article class="card section-card"><div class="flex gap-3"><span class="avatar">${["TH","QB","LP"][i]}</span><div><strong>${["Thu Hà","Quốc Bảo","Lan Phương"][i]}</strong><p class="muted text-xs">Khoảng ${i+1} giờ trước</p></div></div><h2 class="text-base mt-4">${t}</h2><p class="muted text-sm">Cùng trao đổi kinh nghiệm học và ghi nhớ từ vựng hiệu quả nhé.</p><div class="flex gap-2 mt-4"><button class="button small" data-like="${i}">${icon("heart")} <span>${12+i*7}</span></button><button class="button small" data-comment="${i}">${icon("message-circle")} Bình luận</button></div></article>`).join("")}</div><aside class="card section-card h-fit"><h2 class="text-sm">Chủ đề nổi bật</h2>${["#TOPIKII","#HánViệtMỗiNgày","#ThànhNgữ","#HọcCùngNhau"].map(x=>`<button class="dropdown-item" data-topic="${x}">${x}</button>`).join("")}</aside></div>`}
function statsPage(){const vals=[32,48,41,75,62,91,state.today];return header("Thống kê","Xem xu hướng học tập và điểm cần cải thiện.",button("Xuất báo cáo","export-stats"))+`<div class="stats-grid md:grid-cols-4 mb-5">${[["Tổng câu","2.840"],["Độ chính xác","78%"],["Thời gian","18,4 giờ"],["XP",state.xp.toLocaleString()]].map(x=>`<div class="card stat"><strong>${x[1]}</strong><small>${x[0]}</small></div>`).join("")}</div><section class="card section-card"><h2 class="text-sm">Hoạt động 7 ngày</h2><div class="chart">${vals.map(v=>`<div class="bar" style="height:${Math.max(18,v/1.6)}%"><span>${v}</span></div>`).join("")}</div></section>`}
function calendarPage(){const days=Array.from({length:30},(_,i)=>i+1);return header("Lịch học","Lên kế hoạch và duy trì nhịp học đều đặn.",button(`${icon("plus")} Thêm lịch`,"add-schedule","primary"))+`<section class="card section-card"><div class="grid grid-cols-7 gap-2">${["T2","T3","T4","T5","T6","T7","CN"].map(x=>`<div class="text-center muted text-xs">${x}</div>`).join("")}${days.map(d=>`<button class="aspect-square rounded-xl border ${state.calendar.includes(d)?"border-indigo-500 bg-indigo-500/20":"border-white/5 bg-white/[.02]"}" data-calendar-day="${d}"><strong>${d}</strong>${state.calendar.includes(d)?'<small class="block text-[9px] text-indigo-300">Học</small>':""}</button>`).join("")}</div></section>`}
function leaderboardPage(){const me=currentUser(),myName=me.signedIn?me.name:"Bạn";const users=[["Trung Kiên",4820],["Thu Hà",2190],[myName,state.xp,true],["Quốc Bảo",1950],["Lan Phương",1820]];return header("Bảng xếp hạng","Thi đua tích cực cùng cộng đồng mỗi tuần.")+`<div class="card section-card max-w-3xl">${users.sort((a,b)=>b[1]-a[1]).map((u,i)=>`<div class="list-row ${u[2]?"bg-indigo-500/10 rounded-xl":""}"><strong class="w-8 text-center">${i<3?["🥇","🥈","🥉"][i]:i+1}</strong>${u[2]?userAvatar(me):`<span class="avatar">${initials(u[0])}</span>`}<div class="row-main"><strong>${escapeHtml(u[0])} ${u[2]?"(bạn)":""}</strong></div><strong>${u[1].toLocaleString()} XP</strong></div>`).join("")}</div>`}
function settingsPage(){const user=currentUser();return header("Cài đặt","Tùy chỉnh trải nghiệm học tập của bạn.",user.signedIn?button(`${icon("log-out")} Đăng xuất`,"sign-out"):button(`${icon("log-in")} Đăng nhập Google`,"sign-in-google","primary"))+`<form id="settingsForm" class="card section-card max-w-3xl"><div class="profile-settings-head">${userAvatar(user)}<div><strong>${escapeHtml(user.name)}</strong><small>${escapeHtml(user.email||"Chưa đăng nhập Google")}</small></div></div><div class="form-grid"><div class="field"><label>Tên hiển thị</label><input name="name" class="input" value="${escapeAttr(user.name)}" ${user.signedIn?"readonly":""}></div><div class="field"><label>Mục tiêu mỗi ngày</label><input name="dailyGoal" type="number" min="5" max="500" class="input" value="${state.dailyGoal}"></div><div class="field"><label>Giao diện</label><select name="theme" class="input"><option value="dark">Tối</option><option value="midnight">Midnight</option></select></div><div class="field"><label>Thông báo học tập</label><select name="notifications" class="input"><option value="true">Bật</option><option value="false" ${!state.notifications?"selected":""}>Tắt</option></select></div><div class="field full"><label>Giới thiệu</label><textarea class="input" rows="4">Đang chinh phục TOPIK II và từ Hán Việt.</textarea></div></div><div class="flex gap-2 mt-5"><button class="button primary" type="submit">Lưu cài đặt</button><button class="button danger" type="button" data-action="reset-data">Đặt lại dữ liệu</button></div></form>`}

const pageRenderers={home:homePage,courses:coursesPage,decks:decksPage,createDeck:createDeckPage,deckDetail:deckDetailPage,learnSession:learnSessionPage,practice:practicePage,exam:examPage,community:communityPage,stats:statsPage,calendar:calendarPage,leaderboard:leaderboardPage,settings:settingsPage};
function render(){document.body.classList.toggle("learn-mode",state.route==="learnSession");renderNav();renderUserUi();app.innerHTML=(pageRenderers[state.route]||homePage)();window.scrollTo({top:0});}

document.addEventListener("click",e=>{
  const route=e.target.closest("[data-route]")?.dataset.route;if(route){routeTo(route);return}
  if(e.target.closest("[data-close-modal]")||e.target.id==="modal"){closeModal();return}
  const action=e.target.closest("[data-action]")?.dataset.action;
  if(action){
    if(action==="sign-in-google"){openLoginModal();return}
    if(action==="sign-out"){signOut();return}
    if(["study","review","flashcard"].includes(action)){closeModal();state.activeCreatedDeck=null;state.flashIndex=0;state.route="practice";save();render();return}
    if(action==="quiz"){closeModal();state.route="practice";save();render();setTimeout(()=>selectPractice("quiz"),0);return}
    if(action==="dictionary"){closeModal();state.route="practice";save();render();setTimeout(()=>selectPractice("dictionary"),0);return}
    if(action==="stats"){routeTo("stats");return}
    if(action==="lookup"){lookup();return}
    if(action==="next-question"){state.quizIndex=(state.quizIndex+1)%quizQuestions.length;state.quizAnswered=null;save();document.querySelector("#practicePanel").innerHTML=quizPanel();return}
    if(action==="new-deck"){state.deckDraft={title:"",description:"",isPublic:false,suggestions:true,cards:[blankDraftCard()]};state.editingDeckIndex=null;state.route="createDeck";save();render();return}
    if(action==="add-card"){state.deckDraft.cards.push(blankDraftCard());save();render();return}
    if(action==="toggle-public"){state.deckDraft.isPublic=!state.deckDraft.isPublic;save();render();return}
    if(action==="toggle-suggestions"){state.deckDraft.suggestions=!state.deckDraft.suggestions;save();render();return}
    if(action==="cancel-create"){routeTo("decks");return}
    if(action==="delete-draft"){if(confirm("Xóa toàn bộ bản nháp hiện tại?")){state.deckDraft={title:"",description:"",isPublic:false,suggestions:true,cards:[blankDraftCard()]};state.editingDeckIndex=null;save();render();showToast("Đã xóa bản nháp")}return}
    if(action==="save-deck"){saveCreatedDeck();return}
    if(action==="import-cards"){openImportCards();return}
    if(action==="auto-fill"){autoFillDraft();return}
    if(action==="new-course"){simpleForm("Tạo khóa học","Tên khóa học");return}
    if(action==="new-post"){simpleForm("Đăng bài cộng đồng","Tiêu đề bài viết",true);return}
    if(action==="add-schedule"){simpleForm("Thêm lịch học","Nội dung nhắc học");return}
    if(action==="upgrade"){modal("Nâng cấp Pro","<p class='muted'>Đây là bản demo. Bạn có thể kết nối cổng thanh toán ở bước tiếp theo.</p>");return}
    if(action==="reset-data"){localStorage.removeItem("hvq-state");state=freshDefaultState();render();showToast("Đã đặt lại dữ liệu");return}
    if(action==="export-stats"){const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="hanvietquiz-stats.json";a.click();URL.revokeObjectURL(a.href);showToast("Đã xuất báo cáo");return}
    if(action==="start-exam"){startExam();return}
    if(action==="back-to-decks"){state.route="decks";save();render();return}
    if(action==="shuffle-detail"){state.detailSort="original";const count=state.createdDecks[state.activeCreatedDeck]?.cards.length||1;state.detailCardIndex=Math.floor(Math.random()*count);state.detailFlipped=false;save();render();showToast("Đã trộn thẻ");return}
    if(action==="edit-current-card"){state.deckDraft=JSON.parse(JSON.stringify(state.createdDecks[state.activeCreatedDeck]));state.editingDeckIndex=state.activeCreatedDeck;state.route="createDeck";save();render();return}
    if(action==="schedule-review"){showToast("Đã bật lặp lại ngắt quãng","calendar-check");return}
    if(action==="share-deck"){navigator.clipboard?.writeText(location.href);showToast("Đã sao chép liên kết bộ thẻ","link");return}
    if(action==="toggle-deck-bookmark"){showToast("Đã lưu bộ thẻ","bookmark-check");return}
    if(action==="deck-menu"){modal("Tùy chọn bộ thẻ",`<button class="dropdown-item" data-edit-created="${state.activeCreatedDeck}">Chỉnh sửa bộ thẻ</button><button class="dropdown-item" data-action="share-deck">Chia sẻ</button>`);return}
    if(action==="flash-settings"){showToast("Đã mở cài đặt thẻ","sliders-horizontal");return}
    if(action==="show-progress"){document.querySelector("#card-groups")?.scrollIntoView({behavior:"smooth"});return}
    if(action==="start-detail-mode"){showToast("Chế độ học đã sẵn sàng","play");return}
    if(action==="exit-learn"){state.route="deckDetail";save();render();return}
    if(action==="restart-learn"){startLearnSession();return}
    if(action==="learn-settings"){openLearnSettings();return}
    if(action==="edit-learn-card"){state.deckDraft=JSON.parse(JSON.stringify(state.createdDecks[state.activeCreatedDeck]));state.editingDeckIndex=state.activeCreatedDeck;state.route="createDeck";save();render();return}
    if(action==="learn-unknown"){state.learnAnswered="unknown";state.learnUnknown++;save();render();return}
    if(action==="next-learn"){advanceLearnSession();return}
    if(action==="apply-learn-settings"){applyLearnSettings();return}
    if(action==="reset-learn-progress"){resetLearnProgress();return}
  }
  const study=e.target.closest("[data-study]")?.dataset.study;if(study){closeModal();state.activeCreatedDeck=null;state.route="practice";state.flashIndex=(Number(study)-1)%words.length;save();render();return}
  const deck=e.target.closest("[data-deck]")?.dataset.deck;if(deck&&!e.target.closest("[data-study]")){const d=decks.find(x=>x.id==deck);modal(d.name,`<p class="muted">${d.term}</p><div class="mt-4">${progress(Math.round(d.learned/d.total*100))}</div><div class="flex gap-2 mt-5"><button class="button primary" data-study="${d.id}">Học ngay</button><button class="button" data-favorite="${d.id}">${state.favorites.includes(d.id)?"Bỏ yêu thích":"Yêu thích"}</button></div>`);return}
  const editCreated=e.target.closest("[data-edit-created]")?.dataset.editCreated;if(editCreated!==undefined){const i=Number(editCreated);state.deckDraft=JSON.parse(JSON.stringify(state.createdDecks[i]));state.editingDeckIndex=i;state.route="createDeck";save();render();return}
  const deleteCreated=e.target.closest("[data-delete-created]")?.dataset.deleteCreated;if(deleteCreated!==undefined){if(confirm("Xóa bộ thẻ này?")){const i=Number(deleteCreated);state.createdDecks.splice(i,1);if(state.activeCreatedDeck===i)state.activeCreatedDeck=null;else if(Number.isInteger(state.activeCreatedDeck)&&state.activeCreatedDeck>i)state.activeCreatedDeck--;save();render();showToast("Đã xóa bộ thẻ")}return}
  const studyCreated=e.target.closest("[data-study-created]")?.dataset.studyCreated;if(studyCreated!==undefined){openCreatedDeckDetail(Number(studyCreated));return}
  const createdDeck=e.target.closest("[data-created-deck]")?.dataset.createdDeck;if(createdDeck!==undefined&&!e.target.closest("button")){openCreatedDeckDetail(Number(createdDeck));return}
  const removeCard=e.target.closest("[data-remove-card]")?.dataset.removeCard;if(removeCard!==undefined){if(state.deckDraft.cards.length===1){state.deckDraft.cards[0]=blankDraftCard()}else state.deckDraft.cards.splice(Number(removeCard),1);save();render();return}
  const moveCard=e.target.closest("[data-move-card]");if(moveCard){const from=Number(moveCard.dataset.moveCard),to=from+Number(moveCard.dataset.direction);if(to>=0&&to<state.deckDraft.cards.length){[state.deckDraft.cards[from],state.deckDraft.cards[to]]=[state.deckDraft.cards[to],state.deckDraft.cards[from]];save();render()}return}
  const imageCard=e.target.closest("[data-image-card]")?.dataset.imageCard;if(imageCard!==undefined){pickCardImage(Number(imageCard));return}
  const course=e.target.closest("[data-course]")?.dataset.course;if(course){const c=courses.find(x=>x.id==course);modal(c.name,`<p class="muted">${c.level} · ${c.done}/${c.lessons} bài đã hoàn thành</p><div class="mt-4">${progress(Math.round(c.done/c.lessons*100))}</div><button class="button primary mt-5" data-action="study">Tiếp tục học</button>`);return}
  const fav=e.target.closest("[data-favorite]")?.dataset.favorite;if(fav){const id=Number(fav);state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];save();closeModal();showToast("Đã cập nhật yêu thích");return}
  const ptab=e.target.closest("[data-practice-tab]")?.dataset.practiceTab;if(ptab){selectPractice(ptab);return}
  const detailMode=e.target.closest("[data-detail-mode]")?.dataset.detailMode;if(detailMode){if(detailMode==="flashcard"){startLearnSession();return}state.detailMode=detailMode;state.detailFlipped=false;save();render();return}
  const detailNav=e.target.closest("[data-detail-nav]")?.dataset.detailNav;if(detailNav!==undefined){const count=detailCards(state.createdDecks[state.activeCreatedDeck]).length;state.detailCardIndex=(state.detailCardIndex+Number(detailNav)+count)%count;state.detailFlipped=false;save();render();return}
  const setStatus=e.target.closest("[data-set-status]")?.dataset.setStatus;if(setStatus){const card=detailCards(state.createdDecks[state.activeCreatedDeck])[state.detailCardIndex];state.detailProgress[`${state.activeCreatedDeck}:${card.originalIndex}`]=setStatus;if(setStatus==="mastered"){state.xp+=10;state.today+=1}save();render();showToast(setStatus==="mastered"?"Đã thành thạo +10 XP":"Đã cập nhật tiến độ");return}
  const detailStar=e.target.closest("[data-detail-star]")?.dataset.detailStar;if(detailStar!==undefined){const key=`${state.activeCreatedDeck}:${detailStar}`;state.detailStars[key]=!state.detailStars[key];save();render();showToast(state.detailStars[key]?"Đã đánh dấu sao":"Đã bỏ dấu sao");return}
  const learnStar=e.target.closest("[data-learn-star]")?.dataset.learnStar;if(learnStar!==undefined){const key=`${state.activeCreatedDeck}:${learnStar}`;state.detailStars[key]=!state.detailStars[key];save();render();return}
  const learnAnswer=e.target.closest("[data-learn-answer]")?.dataset.learnAnswer;if(learnAnswer!==undefined&&state.learnAnswered===null){state.learnAnswered=Number(learnAnswer);const cardIndex=state.learnOrder[state.learnIndex],correct=state.learnOptions[state.learnAnswered].cardIndex===cardIndex;if(correct){state.learnCorrect++;state.xp+=10;state.today++}save();render();if(correct&&state.learnSettings.autoAdvance)setTimeout(()=>{if(state.route==="learnSession"&&state.learnAnswered!==null)advanceLearnSession()},700);return}
  const jumpCard=e.target.closest("[data-jump-card]")?.dataset.jumpCard;if(jumpCard!==undefined&&!e.target.closest("button")){const cards=detailCards(state.createdDecks[state.activeCreatedDeck]);state.detailCardIndex=Math.max(0,cards.findIndex(c=>c.originalIndex===Number(jumpCard)));state.detailFlipped=false;save();render();window.scrollTo({top:0,behavior:"smooth"});return}
  if(e.target.closest("#detailFlashcard")&&!e.target.closest("button")){state.detailFlipped=!state.detailFlipped;save();render();return}
  const courseFilter=e.target.closest("[data-filter-course]")?.dataset.filterCourse;if(courseFilter!==undefined){document.querySelectorAll("[data-filter-course]").forEach(x=>x.classList.toggle("active",x.dataset.filterCourse===courseFilter));document.querySelector("#courseResults").innerHTML=courseFilter==="2"?'<p class="empty card">Bạn chưa hoàn thành khóa học nào.</p>':courseRows();return}
  if(e.target.closest("#flashcard")){e.target.closest("#flashcard").classList.toggle("flipped");return}
  const rate=e.target.closest("[data-rate]")?.dataset.rate;if(rate){const source=currentFlashcards();state.flashIndex=((state.flashIndex||0)+1)%source.length;if(rate==="easy"){state.xp+=10;state.today+=1}save();document.querySelector("#practicePanel").innerHTML=flashcardPanel();showToast(rate==="easy"?"Đã ghi nhớ +10 XP":"Đã xếp lịch ôn lại");return}
  const answer=e.target.closest("[data-answer]")?.dataset.answer;if(answer!==undefined){const q=quizQuestions[state.quizIndex%quizQuestions.length];state.quizAnswered=Number(answer);if(Number(answer)===q.answer){state.quizScore+=10;state.xp+=10;showToast("Chính xác! +10 XP")}else showToast("Chưa đúng, xem đáp án nhé","circle-x");save();document.querySelector("#practicePanel").innerHTML=quizPanel();return}
  const calendar=e.target.closest("[data-calendar-day]")?.dataset.calendarDay;if(calendar){const d=Number(calendar);state.calendar=state.calendar.includes(d)?state.calendar.filter(x=>x!==d):[...state.calendar,d];save();render();return}
  const exam=e.target.closest("[data-exam]")?.dataset.exam;if(exam!==undefined){startExam(Number(exam));return}
  const like=e.target.closest("[data-like]");if(like){const span=like.querySelector("span:last-child");span.textContent=Number(span.textContent)+1;like.classList.add("text-pink-400");return}
  const comment=e.target.closest("[data-comment]");if(comment){simpleForm("Viết bình luận","Nội dung bình luận",true);return}
  const speak=e.target.closest("[data-speak]")?.dataset.speak;if(speak){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(speak));return}
});

document.addEventListener("input",e=>{if(e.target.id==="deckSearch")filterDecks();if(e.target.id==="dictionaryInput"&&e.target.value.length>1)lookup();if(e.target.matches("[data-draft-meta]")){state.deckDraft[e.target.dataset.draftMeta]=e.target.value;save()}if(e.target.matches("[data-card-field]")){const editor=e.target.closest("[data-card-index]");if(editor){state.deckDraft.cards[Number(editor.dataset.cardIndex)][e.target.dataset.cardField]=e.target.value;save()}}});
document.addEventListener("change",e=>{if(e.target.id==="deckSort")filterDecks();if(e.target.id==="detailSort"){state.detailSort=e.target.value;state.detailCardIndex=0;state.detailFlipped=false;save();render()}});
document.addEventListener("submit",e=>{e.preventDefault();if(e.target.id==="settingsForm"){const fd=new FormData(e.target);if(!state.user?.signedIn)state.user={...state.user,name:fd.get("name")||"Khách"};state.dailyGoal=Number(fd.get("dailyGoal"));state.notifications=fd.get("notifications")==="true";save();render();showToast("Đã lưu cài đặt")}else if(e.target.id==="fillBlankForm"){checkFillBlank()}else{closeModal();showToast("Đã lưu thành công")}});
document.addEventListener("keydown",e=>{if(state.route!=="deckDetail"||state.detailMode!=="flashcard"||["INPUT","TEXTAREA","SELECT"].includes(document.activeElement.tagName))return;if([" ","Enter"].includes(e.key)){e.preventDefault();state.detailFlipped=!state.detailFlipped}else if(e.key==="ArrowLeft"){const n=detailCards(state.createdDecks[state.activeCreatedDeck]).length;state.detailCardIndex=(state.detailCardIndex-1+n)%n;state.detailFlipped=false}else if(e.key==="ArrowRight"){const n=detailCards(state.createdDecks[state.activeCreatedDeck]).length;state.detailCardIndex=(state.detailCardIndex+1)%n;state.detailFlipped=false}else return;save();render()});
document.addEventListener("keydown",e=>{if(state.route!=="learnSession"||["INPUT","TEXTAREA","SELECT"].includes(document.activeElement.tagName))return;if(state.learnAnswered===null&&!state.learnSettings.fillBlank&&["1","2","3","4"].includes(e.key)){const answer=Number(e.key)-1;if(state.learnOptions[answer]){state.learnAnswered=answer;const cardIndex=state.learnOrder[state.learnIndex],correct=state.learnOptions[answer].cardIndex===cardIndex;if(correct){state.learnCorrect++;state.xp+=10;state.today++}save();render();if(correct&&state.learnSettings.autoAdvance)setTimeout(()=>{if(state.route==="learnSession"&&state.learnAnswered!==null)advanceLearnSession()},700)}}else if(state.learnAnswered===null&&e.key==="5"){state.learnAnswered="unknown";state.learnUnknown++;save();render()}else if(state.learnAnswered!==null&&e.key==="Enter"){advanceLearnSession()}});

function selectPractice(name){document.querySelectorAll("[data-practice-tab]").forEach(x=>x.classList.toggle("active",x.dataset.practiceTab===name));document.querySelector("#practicePanel").innerHTML=name==="quiz"?quizPanel():name==="dictionary"?dictionaryPanel():flashcardPanel()}
function startCreatedDeck(index){const deck=state.createdDecks[index];if(!deck?.cards?.length){showToast("Bộ thẻ chưa có nội dung","circle-alert");return}closeModal();state.activeCreatedDeck=index;state.flashIndex=0;state.route="practice";save();render()}
function openCreatedDeckDetail(index){const deck=state.createdDecks[index];if(!deck?.cards?.length){showToast("Bộ thẻ chưa có nội dung","circle-alert");return}closeModal();state.activeCreatedDeck=index;state.detailCardIndex=0;state.detailFlipped=false;state.detailMode="flashcard";state.route="deckDetail";save();render()}
function startLearnSession(){const deck=state.createdDecks[state.activeCreatedDeck];if(!deck?.cards?.length){showToast("Bộ thẻ chưa có nội dung","circle-alert");return}let order=deck.cards.map((_,i)=>i);if(state.learnSettings.starredOnly)order=order.filter(i=>isDetailStarred(i));if(state.learnSettings.unmasteredOnly)order=order.filter(i=>detailStatus(i)!=="mastered");if(!state.learnSettings.inOrder)order=shuffled(order);state.learnOrder=order;state.learnIndex=0;state.learnCompleted=0;state.learnCorrect=0;state.learnUnknown=0;state.learnAnswered=null;state.learnOptions=order.length?buildLearnOptions(order[0]):[];state.route="learnSession";save();render()}
function advanceLearnSession(){const cardIndex=state.learnOrder[state.learnIndex];const correct=state.learnAnswered==="fill-correct"||(Number.isInteger(state.learnAnswered)&&state.learnOptions[state.learnAnswered]?.cardIndex===cardIndex);state.detailProgress[`${state.activeCreatedDeck}:${cardIndex}`]=correct?"mastered":"learning";state.learnCompleted++;state.learnIndex++;state.learnAnswered=null;if(state.learnIndex<state.learnOrder.length)state.learnOptions=buildLearnOptions(state.learnOrder[state.learnIndex]);save();render()}
function openLearnSettings(){const s=state.learnSettings,deck=state.createdDecks[state.activeCreatedDeck],starred=deck.cards.filter((_,i)=>isDetailStarred(i)).length,unmastered=deck.cards.filter((_,i)=>detailStatus(i)!=="mastered").length;modal("Cài đặt học tập",`<p class="muted text-xs mb-5">Tùy chỉnh cách bạn muốn học và kiểm tra</p><div class="learn-settings">
  <section class="settings-section"><h3>Chế độ trả lời</h3>
    ${settingCheck("answerDefinition","Trả lời bằng định nghĩa","hiển thị thuật ngữ",s.answerDefinition)}
    ${settingCheck("answerTerm","Trả lời bằng thuật ngữ","hiển thị định nghĩa",s.answerTerm)}
    <p class="setting-help">* Phải chọn ít nhất một chế độ trả lời</p>
  </section>
  <section class="settings-section"><h3>Lọc từ vựng</h3>
    ${settingCheck("starredOnly",`⭐ Chỉ học từ đánh dấu sao (${starred} từ)`,"",s.starredOnly)}
    ${settingCheck("unmasteredOnly",`🎓 Chỉ học từ chưa thuộc (${unmastered} từ)`,"",s.unmasteredOnly)}
  </section>
  <section class="settings-section"><h3>Thứ tự học</h3>${settingCheck("inOrder","Học theo thứ tự (không xáo trộn)","",s.inOrder)}</section>
  <section class="settings-section"><h3>Tùy chọn trả lời</h3>${settingCheck("acceptSynonyms","Chấp nhận từ đồng nghĩa làm đáp án","Khi bật, bạn có thể trả lời bằng bất kỳ từ đồng nghĩa nào",s.acceptSynonyms)}</section>
  <section class="settings-section"><h3>Tùy chọn hành vi</h3>${settingCheck("autoAdvance","Tự động tiếp tục khi trả lời đúng","Khi bật, tự động chuyển sang câu tiếp theo khi trả lời đúng",s.autoAdvance)}</section>
  <section class="settings-section"><h3>Loại câu hỏi</h3>
    ${settingCheck("fillBlank","Điền từ (Fill in the blank)","",s.fillBlank)}
    ${settingCheck("multipleChoice","Trắc nghiệm 4 đáp án","",s.multipleChoice)}
    <p class="setting-help">* Phải chọn ít nhất một loại câu hỏi</p>
  </section>
  <div class="settings-footer"><button class="button" data-action="reset-learn-progress">${icon("rotate-ccw")} Reset tiến độ học</button><button class="button primary" data-action="apply-learn-settings">Áp dụng</button></div>
  </div>`);document.querySelector(".modal-card").classList.add("learn-settings-modal")}
function settingCheck(name,label,help,checked){return `<label class="setting-choice"><input type="checkbox" data-learn-setting="${name}" ${checked?"checked":""}><span>${label}${help?`<small>${help}</small>`:""}</span></label>`}
function applyLearnSettings(){const next={};document.querySelectorAll("[data-learn-setting]").forEach(input=>next[input.dataset.learnSetting]=input.checked);if(!next.answerDefinition&&!next.answerTerm){showToast("Hãy chọn ít nhất một chế độ trả lời","circle-alert");return}if(!next.fillBlank&&!next.multipleChoice){showToast("Hãy chọn ít nhất một loại câu hỏi","circle-alert");return}if(next.answerDefinition&&next.answerTerm)next.answerTerm=false;if(next.fillBlank&&next.multipleChoice)next.fillBlank=false;state.learnSettings={...state.learnSettings,...next};closeModal();startLearnSession();showToast("Đã áp dụng cài đặt")}
function resetLearnProgress(){if(!confirm("Reset toàn bộ tiến độ học của bộ thẻ này?"))return;const prefix=`${state.activeCreatedDeck}:`;Object.keys(state.detailProgress).filter(key=>key.startsWith(prefix)).forEach(key=>delete state.detailProgress[key]);save();showToast("Đã reset tiến độ học");closeModal();startLearnSession()}
function normalizeLearnText(value){return String(value||"").trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[.,;:!?()[\]{}'"]/g,"").replace(/\s+/g," ")}
function checkFillBlank(){if(state.learnAnswered!==null)return;const deck=state.createdDecks[state.activeCreatedDeck],card=deck.cards[state.learnOrder[state.learnIndex]],typed=normalizeLearnText(document.querySelector("#fillBlankAnswer")?.value),answers=[learnAnswer(card)];if(state.learnSettings.acceptSynonyms&&card.synonyms)answers.push(...card.synonyms.split(/[;,]/));const correct=answers.some(x=>normalizeLearnText(x)===typed);state.learnAnswered=correct?"fill-correct":"fill-wrong";if(correct){state.learnCorrect++;state.xp+=10;state.today++}save();render();if(correct&&state.learnSettings.autoAdvance)setTimeout(()=>{if(state.route==="learnSession"&&state.learnAnswered==="fill-correct")advanceLearnSession()},700)}
function lookup(){const q=(document.querySelector("#dictionaryInput")?.value||"").trim().toLowerCase();const found=words.filter(w=>[w.term,w.reading,w.meaning].some(x=>x.toLowerCase().includes(q)));document.querySelector("#dictionaryResults").innerHTML=found.length?found.map(w=>`<div class="card list-row"><strong class="text-2xl text-indigo-400">${w.term}</strong><div class="row-main"><strong>${w.reading}</strong><small>${w.meaning}</small></div><button class="icon-button" data-speak="${w.term}">${icon("volume-2")}</button></div>`).join(""):'<p class="empty">Không tìm thấy từ phù hợp.</p>'}
function filterDecks(){const q=(document.querySelector("#deckSearch").value||"").toLowerCase();const sort=document.querySelector("#deckSort").value;const list=decks.filter(d=>(d.name+d.term).toLowerCase().includes(q)).sort((a,b)=>sort==="progress"?b.learned/b.total-a.learned/a.total:a.name.localeCompare(b.name));document.querySelector("#deckResults").innerHTML=`<div class="deck-grid">${list.map(d=>`<article class="card deck-card card-hover" data-deck="${d.id}"><span class="text-xl">${d.icon}</span><h3>${d.name}</h3><p>${d.term}</p><div class="mt-3">${progress(Math.round(d.learned/d.total*100))}</div></article>`).join("")}</div>`}
function simpleForm(title,label,long=false){modal(title,`<form><div class="field"><label>${label}</label>${long?'<textarea required class="input" rows="6"></textarea>':'<input required class="input">'}</div><button class="button primary mt-5">Lưu</button></form>`)}
function startExam(id=0){state.quizIndex=0;state.quizScore=0;state.quizAnswered=null;save();modal("Bắt đầu luyện thi",`<p class="muted mb-4">Đề ${id+1} đã sẵn sàng. Đồng hồ sẽ bắt đầu khi bạn nhấn nút bên dưới.</p><button class="button primary" data-action="quiz">Bắt đầu ngay</button>`)}
function saveCreatedDeck(){const title=state.deckDraft.title.trim();const validCards=state.deckDraft.cards.filter(c=>c.term.trim()||c.definition.trim());if(!title){showToast("Hãy nhập tiêu đề bộ thẻ","circle-alert");document.querySelector("[data-draft-meta=title]")?.focus();return}if(!validCards.length){showToast("Hãy nhập ít nhất một thẻ","circle-alert");return}const deck={...JSON.parse(JSON.stringify(state.deckDraft)),cards:validCards,updatedAt:new Date().toISOString()};if(Number.isInteger(state.editingDeckIndex))state.createdDecks[state.editingDeckIndex]=deck;else state.createdDecks.unshift(deck);state.editingDeckIndex=null;state.deckDraft={title:"",description:"",isPublic:false,suggestions:true,cards:[blankDraftCard()]};state.route="decks";save();render();showToast("Đã tạo bộ thẻ thành công")}
function openImportCards(){modal("Nhập",`<p class="muted text-xs mb-5">Chép và dán dữ liệu từ Word, Excel, Google Docs, v.v.</p>
  <textarea id="bulkImportText" class="bulk-import-box" placeholder="Từ 1	Định nghĩa 1	Phát âm (nếu có)	Loại từ (nếu có)	Ví dụ (nếu có)	Từ đồng nghĩa (nếu có)&#10;Từ 2	Định nghĩa 2	Phát âm (nếu có)	Loại từ (nếu có)	Ví dụ (nếu có)	Từ đồng nghĩa (nếu có)"></textarea>
  <div class="import-options">
    <div class="radio-group"><strong>Giữa thuật ngữ và định nghĩa</strong>
      <label class="radio-line"><input type="radio" name="fieldDelimiter" value="tab" checked> Tab</label>
      <label class="radio-line"><input type="radio" name="fieldDelimiter" value="comma"> Phẩy</label>
      <label class="radio-line"><input type="radio" name="fieldDelimiter" value="custom"> Tùy chọn <input id="customFieldDelimiter" class="custom-delimiter" maxlength="5" placeholder="VD: |"></label>
    </div>
    <div class="radio-group"><strong>Giữa các thẻ</strong>
      <label class="radio-line"><input type="radio" name="cardDelimiter" value="newline" checked> Dòng mới</label>
      <label class="radio-line"><input type="radio" name="cardDelimiter" value="semicolon"> Chấm phẩy</label>
      <label class="radio-line"><input type="radio" name="cardDelimiter" value="custom"> Tùy chọn <input id="customCardDelimiter" class="custom-delimiter" maxlength="5" placeholder="VD: ||"></label>
    </div>
  </div>
  <div id="importPreview" class="import-preview"><h4>Xem trước</h4><p class="muted text-xs">Dán dữ liệu để xem cách các thẻ được tách.</p></div>
  <div class="import-footer"><button class="button" data-close-modal>Hủy nhập</button><button class="button primary" id="confirmImport" disabled>Nhập</button></div>`);
  const card=document.querySelector(".modal-card");card.classList.add("import-modal");
  const refresh=()=>refreshImportPreview();
  document.querySelector("#bulkImportText").addEventListener("input",refresh);
  document.querySelectorAll('input[name="fieldDelimiter"], input[name="cardDelimiter"]').forEach(x=>x.addEventListener("change",()=>{document.querySelector("#customFieldDelimiter").classList.toggle("show",selectedImportOption("fieldDelimiter")==="custom");document.querySelector("#customCardDelimiter").classList.toggle("show",selectedImportOption("cardDelimiter")==="custom");refresh()}));
  document.querySelector("#customFieldDelimiter").addEventListener("input",refresh);
  document.querySelector("#customCardDelimiter").addEventListener("input",refresh);
  document.querySelector("#confirmImport").onclick=confirmBulkImport;
}
function selectedImportOption(name){return document.querySelector(`input[name="${name}"]:checked`)?.value}
function importDelimiter(kind){const option=selectedImportOption(kind==="field"?"fieldDelimiter":"cardDelimiter");if(kind==="field"){if(option==="tab")return "\t";if(option==="comma")return ",";return document.querySelector("#customFieldDelimiter")?.value||""}if(option==="newline")return "\n";if(option==="semicolon")return ";";return document.querySelector("#customCardDelimiter")?.value||""}
function parseBulkImport(){const raw=document.querySelector("#bulkImportText")?.value.replace(/\r\n/g,"\n").trim()||"";const fieldDelimiter=importDelimiter("field"),cardDelimiter=importDelimiter("card");if(!raw||!fieldDelimiter||!cardDelimiter)return[];return raw.split(cardDelimiter).map(x=>x.trim()).filter(Boolean).map(row=>{const parts=row.split(fieldDelimiter).map(x=>x.trim());return {...blankDraftCard(),term:parts[0]||"",definition:parts[1]||"",pronunciation:parts[2]||"",wordType:parts[3]||"",example:parts[4]||"",synonyms:parts.slice(5).join(fieldDelimiter)||""}}).filter(card=>card.term||card.definition)}
function refreshImportPreview(){const cards=parseBulkImport();const preview=document.querySelector("#importPreview"),confirm=document.querySelector("#confirmImport");if(!preview||!confirm)return;confirm.disabled=!cards.length;preview.innerHTML=cards.length?`<h4>Xem trước ${cards.length} thẻ</h4>${cards.slice(0,4).map((card,i)=>`<div class="preview-row"><strong>${i+1}</strong><span title="${escapeAttr(card.term)}">${escapeHtml(card.term||"—")}</span><span title="${escapeAttr(card.definition)}">${escapeHtml(card.definition||"—")}</span></div>`).join("")}${cards.length>4?`<p class="muted text-xs mt-2">… và ${cards.length-4} thẻ khác</p>`:""}`:'<h4>Xem trước</h4><p class="muted text-xs">Dữ liệu chưa hợp lệ với dấu phân cách đang chọn.</p>'}
function confirmBulkImport(){const cards=parseBulkImport();if(!cards.length){showToast("Không có dữ liệu hợp lệ","circle-alert");return}state.deckDraft.cards=cards;save();document.querySelector(".modal-card")?.classList.remove("import-modal");closeModal();render();showToast(`Đã nhập ${cards.length} thẻ`)}
function autoFillDraft(){let changed=0;const suggestions={"經濟":"Kinh tế","社會":"Xã hội","文化":"Văn hóa","自然":"Tự nhiên","學習":"Học tập","勉強":"Học tập, nỗ lực"};state.deckDraft.cards.forEach(card=>{if(card.term&&!card.definition&&suggestions[card.term]){card.definition=suggestions[card.term];changed++}if(card.term&&!card.pronunciation){const word=words.find(w=>w.term===card.term);if(word){card.pronunciation=word.reading;changed++}}});if(!state.deckDraft.cards.some(c=>c.term)){state.deckDraft.cards=[{...blankDraftCard(),term:"經濟",definition:"Kinh tế",pronunciation:"Kinh tế",wordType:"Danh từ",example:"經濟發展 — Phát triển kinh tế",synonyms:"kinh tài"},{...blankDraftCard(),term:"社會",definition:"Xã hội",pronunciation:"Xã hội",wordType:"Danh từ",example:"現代社會 — Xã hội hiện đại",synonyms:"cộng đồng"}];changed=2}save();render();showToast(changed?`Đã gợi ý cho ${changed} mục`:"Chưa có mục phù hợp để gợi ý")}
function pickCardImage(index){const input=document.createElement("input");input.type="file";input.accept="image/*";input.onchange=()=>{const file=input.files[0];if(!file)return;if(file.size>1500000){showToast("Ảnh cần nhỏ hơn 1,5 MB","circle-alert");return}const reader=new FileReader();reader.onload=()=>{state.deckDraft.cards[index].image=reader.result;save();render();showToast("Đã thêm ảnh")};reader.readAsDataURL(file)};input.click()}

document.querySelector("#notificationButton").onclick=e=>{e.stopPropagation();document.querySelector("#notificationMenu").classList.toggle("show")};
document.querySelector("#profileButton").onclick=e=>{e.stopPropagation();document.querySelector("#profileMenu").classList.toggle("show")};
document.querySelector("#notificationMenu").innerHTML=`<strong class="block p-3">Thông báo</strong><button class="dropdown-item">🔥 Chuỗi ${state.streak} ngày — tiếp tục nhé!</button><button class="dropdown-item">TOPIK II vừa có bài học mới</button>`;
document.querySelector("#profileMenu").innerHTML=`<button class="dropdown-item" data-route="settings">Hồ sơ & cài đặt</button><button class="dropdown-item" data-action="upgrade">Nâng cấp Pro</button><button class="dropdown-item text-red-400">Đăng xuất</button>`;
document.querySelector("#searchButton").onclick=()=>modal("Tìm kiếm nhanh",`<input id="globalSearch" class="input" autofocus placeholder="Tìm khóa học, bộ từ, từ vựng..."><div class="search-results">${decks.slice(0,3).map(d=>`<button class="dropdown-item" data-deck="${d.id}">${d.icon} ${d.name}</button>`).join("")}</div>`);
document.addEventListener("click",e=>{if(!e.target.closest("#notificationButton")&&!e.target.closest("#notificationMenu"))document.querySelector("#notificationMenu").classList.remove("show");if(!e.target.closest("#profileButton")&&!e.target.closest("#profileMenu"))document.querySelector("#profileMenu").classList.remove("show")});

render();
